init_clang19_env now uses the executable sysroot/bin/testcpu to check if the current CPU can execute binaries compiled for arm64 CPUs

diff --git a/sysroot/bin/init_clang19_env b/sysroot/bin/init_clang19_env
--- a/sysroot/bin/init_clang19_env
+++ b/sysroot/bin/init_clang19_env
@@ -35,6 +35,12 @@
 #    if 'uname -m" returns "armv8*" the script sets CPU_TYPE now to aarch64
 #    the script now prints warning messages if a directory from the NDK is missing
 #
+#  06.06.2025 v1.4.0 /bs
+#    the script now uses the executable sysroot/bin/testcpu to check if the current CPU can execute binaries compiled for arm64 CPUs
+#    added the parameter nocpucheck
+#    the value for CPU_TYPE is now hardcoded in the script
+#    the parameter are now processed BEFORE setting the variables
+#
 
 __TRUE=0
 __FALSE=1
@@ -43,37 +49,51 @@ STANDALONE_SCRIPT=${__FALSE}
 
 CONTINUE=${__TRUE}
 
-PRINT_EXAMPLES=${__FALSE}
+if [ ${CONTINUE} = ${__TRUE} ] ; then
 
-alias LogDebugMsg='[ "${DEBUG}"x != ""x ] && echo "DEBUG: $*" >&2 '
+# this variable is set to ture if the parameter "examples" is used
+#
+  PRINT_EXAMPLES=${__FALSE}
 
-TEST="$( which test )"
+  alias LogDebugMsg='[ "${DEBUG}"x != ""x ] && echo "DEBUG: $*" >&2 '
+
+
+# the test binary to use
+#
+  TEST="$( which test )"
 
 # this is NOT a supported environment variable -> use this code to avoid adding the variable to the list of supported environment variables in the usage output
 #
-[ "${TEST}"x = ""x ] && TEST="test"
+  [ "${TEST}"x = ""x ] && TEST="test"
 
 
-THIS_SCRIPT="$0"
+# set to ${__FALSE} to disable the CPU check
+#
+  CHECK_CPU="${CHECK_CPU:=${__TRUE}}"
+
+
+  THIS_SCRIPT="$0"
 
 # check if this script was sourced in
 #
-if [[ "${THIS_SCRIPT}" != */init_clang*_env ]] ; then
-  THIS_SCRIPT="/data/local/tmp/sysroot/bin/init_clang19_env"
-else
-  CLANG_SYSROOT="$( cd "${THIS_SCRIPT%/bin/*}" && pwd )"
-fi
+  if [[ "${THIS_SCRIPT}" != */init_clang*_env ]] ; then
+    THIS_SCRIPT="/data/local/tmp/sysroot/bin/init_clang19_env"
+  else
+    CLANG_SYSROOT="$( cd "${THIS_SCRIPT%/bin/*}" && pwd )"
+  fi
 
 # ---------------------------------------------------------------------
 # the variable TMPDIR is used by the /sytem/bin/sh to get the default directory for temporary files
 #
-TMPDIR="${TMPDIR:=/data/local/tmp}"
-export TMPDIR
+  TMPDIR="${TMPDIR:=/data/local/tmp}"
+  export TMPDIR
+
+fi
 
 # ---------------------------------------------------------------------
 
 function add_path {
-  
+
   while [ $# -ne 0 ] ; do
     CUR_DIR="$1"
     shift
@@ -82,7 +102,7 @@ function add_path {
 }
 
 function add_library_path {
-  
+
   while [ $# -ne 0 ] ; do
     CUR_DIR="$1"
     shift
@@ -91,99 +111,15 @@ function add_library_path {
 }
 
 # ---------------------------------------------------------------------
-#  sysroot for the clang binaries and the other tools (make, etc)
+# main function starts here
 #
-CLANG_SYSROOT="${CLANG_SYSROOT:=/data/local/tmp/sysroot}"
-
-echo "The toolchain directory used is \"${CLANG_SYSROOT}\" "
-
-# ---------------------------------------------------------------------
-
-# certificate file
-#
-DEFAULT_SSL_CERT_FILE="${CLANG_SYSROOT}/etc/security/ca-certificates.crt"
-
-# sysroot for the programs compiled with clang
-# 
-TARGET_ROOT="${TARGET_ROOT:=/data/local/tmp/develop/sysroot}"
-
-# clang version 
-#
-CLANG_VERSION="${CLANG_VERSION:=19}"
-
-# directory with the files for clang
-# 
-CLANG_DIR="${CLANG_DIR:=${CLANG_SYSROOT}/usr/clang${CLANG_VERSION}}"
-
-# NDK to use
-
-NDK="${NDK:=r27b}"
-
-# directory with the files from the NDK
-#
-NDK_DIR="${NDK_DIR:=${CLANG_SYSROOT}/usr/ndk/${NDK}}"
-
-
-# sysrot directory from the NDK
-#
-SYSROOT="${SYSROOT:=${NDK_DIR}/sysroot}"
-
-API=${API:=31}
-   
-# magiskpolicy is optional used to change SELinux permissions 
-#
-MAGISKPOLICY="$( which magiskpolicy 2>/dev/null )"
-
-
-
-MANPATH=${CLANG_SYSROOT}/usr/share/man
-
-HOME="${CLANG_SYSROOT}/home/shell"
-
-TERMINFO="${CLANG_SYSROOT}/usr/share/terminfo"
-
-add_path "${CLANG_SYSROOT}/usr/bin" "${CLANG_SYSROOT}/bin"
-
-add_library_path "${CLANG_SYSROOT}/usr/lib"
-
-export HOME TERMINFO PATH LD_LIBRARY_PATH MAN_PATH
-
-# ---------------------------------------------------------------------
-
-CPU_TYPE="${CPU_TYPE:=$( uname -m )}"
-
-CPU_TYPE="${CPU_TYPE:=$( uname -m )}"
-if [[ ${CPU_TYPE} == armv8* ]] ; then
-  echo "The CPU type is \"${CPU_TYPE}\" - using the directories for the CPU type \"aarch64\" "
-  CPU_TYPE="aarch64"
-fi
-  
-# ---------------------------------------------------------------------
-
-if [ ${CONTINUE} = ${__TRUE} ] ; then
-
-  ROOT_ACCESS_AVAILABLE=${__FALSE}
-  ROOT_PREFIX=""
-  
-  CUR_USER="$( id -un )"
-
-  if [ "${CUR_USER}"x = "root"x ] ; then
-    ROOT_ACCESS_AVAILABLE=${__TRUE}
-  else 
-    su - -c id 2>/dev/null 1>/dev/null 
-    if [ $? -eq 0 ] ; then
-      ROOT_ACCESS_AVAILABLE=${__TRUE}
-      ROOT_PREFIX="su - -c "
-    fi
-  fi  
-fi
 
 if [ ${CONTINUE} = ${__TRUE} ] ; then
 
   while [ $# -ne 0 ] ; do
     CUR_PARAMETER="$1"
     shift
-    
+
     case ${CUR_PARAMETER} in
  
       -h | --help | help )
@@ -197,12 +133,13 @@ $( grep ":=" ${THIS_SCRIPT} | grep -v SUPPORTED_ENV_VARIABLES )
            SUPPORTED_ENV_VARIABLES=""
         fi
         cat <<EOT
-        
-Usage: . ${THIS_SCRIPT} [-h|--help] [init] [var=value] [examples]
+
+Usage: . ${THIS_SCRIPT} [-h|--help] [init] [var=value] [examples] [nocpucheck]
  
 init        - clear the used enviroment variables at script start
 var=value   - set the environment variable "var" to "value" at start of the script
 examples    - print compile examples 
+nocpucheck  - disable the CPU check
 
 ${SUPPORTED_ENV_VARIABLES}
 
@@ -215,16 +152,21 @@ EOT
         CONTINUE=${__FALSE}
       ;;
 
+      nocpucheck | no_cpucheck | no_cpu_check )
+        CHECK_CPU=${__FALSE}
+        ;;
+
       examples | example | ex )
         PRINT_EXAMPLES=${__TRUE}
         ;;
 
       init | clear )
         echo "Clearing all used variables ..."
-        unset CFLAGS CPPFLAGS CXXFLAGS LDFLAGS  API SYSROOT TARGET_ROOT CPU_TYPE CLANG_DIR CLANG_VERSION NDK_DIR
+        unset CFLAGS CPPFLAGS CXXFLAGS LDFLAGS API SYSROOT TARGET_ROOT CLANG_DIR CLANG_VERSION NDK_DIR
         ;;
-    
+
       *=* )
+        echo "Executing now \"${CUR_PARAMETER}\" ..."
         eval ${CUR_PARAMETER}
         if [ $? -ne 0 ] ; then
           echo "ERROR: Error executing \"${CUR_PARAMETER}\" "
@@ -238,20 +180,134 @@ EOT
         ;;
     esac
   done
+fi
+
+# ---------------------------------------------------------------------
+
+if [ ${CONTINUE} = ${__TRUE} ] ; then
+
+#
+#  sysroot for the clang binaries and the other tools (make, etc)
+#
+  CLANG_SYSROOT="${CLANG_SYSROOT:=/data/local/tmp/sysroot}"
+
+  echo "The toolchain directory used is \"${CLANG_SYSROOT}\" "
+
+# certificate file
+#
+  DEFAULT_SSL_CERT_FILE="${CLANG_SYSROOT}/etc/security/ca-certificates.crt"
+
+# optional additional sysroot for additional libaries and include files
+# 
+  TARGET_ROOT="${TARGET_ROOT:=/data/local/tmp/develop/sysroot}"
+
+# clang version 
+#
+  CLANG_VERSION="${CLANG_VERSION:=19}"
+
+# directory with the files for clang
+# 
+  CLANG_DIR="${CLANG_DIR:=${CLANG_SYSROOT}/usr/clang${CLANG_VERSION}}"
+
+# NDK to use
+#
+  NDK="${NDK:=r27b}"
+
+# directory with the files from the NDK
+#
+  NDK_DIR="${NDK_DIR:=${CLANG_SYSROOT}/usr/ndk/${NDK}}"
+
+
+# sysrot directory from the NDK
+#
+  SYSROOT="${SYSROOT:=${NDK_DIR}/sysroot}"
+
+# API version 
+#
+  API=${API:=31}
+ 
+# magiskpolicy is optional used to change SELinux permissions 
+#
+  MAGISKPOLICY="$( which magiskpolicy 2>/dev/null )"
+
+
+  MANPATH=${CLANG_SYSROOT}/usr/share/man
+
+  HOME="${CLANG_SYSROOT}/home/shell"
+
+  TERMINFO="${CLANG_SYSROOT}/usr/share/terminfo"
+
+  add_path "${CLANG_SYSROOT}/usr/bin" "${CLANG_SYSROOT}/bin"
+
+  add_library_path "${CLANG_SYSROOT}/usr/lib"
+
+  export HOME TERMINFO PATH LD_LIBRARY_PATH MAN_PATH
 
 fi
+
+# ---------------------------------------------------------------------
+
+if [ ${CONTINUE} = ${__TRUE} ] ; then
+
+  ROOT_ACCESS_AVAILABLE=${__FALSE}
+  ROOT_PREFIX=""
+
+  CUR_USER="$( id -un )"
+
+  if [ "${CUR_USER}"x = "root"x ] ; then
+    ROOT_ACCESS_AVAILABLE=${__TRUE}
+  else 
+    su - -c id 2>/dev/null 1>/dev/null 
+    if [ $? -eq 0 ] ; then
+      ROOT_ACCESS_AVAILABLE=${__TRUE}
+      ROOT_PREFIX="su - -c "
+    fi
+  fi
+fi
+
+# ---------------------------------------------------------------------
+
+if [ ${CONTINUE} = ${__TRUE} ] ; then
+
+#
+# 06.06.2025 /bs : CPU_TYPE is hardcoded now; CUR_CPU_TYPE is only used for messages
+#
+  CPU_TYPE="aarch64"
+
+  CUR_CPU_TYPE="$( uname -m )"
+
+#
+# check, if the current CPU can execute binaries compiled for arm64
+#
+  if [ ${CHECK_CPU}x != ${__FALSE}x ] ; then
+    CHECK_CPU_TEST_PROGRAM="${CLANG_SYSROOT}/bin/testcpu"
+    if [ -x "${CHECK_CPU_TEST_PROGRAM}" ] ; then
+      echo "Checking if the current CPU can execute binaries for arm64 CPUs using the binary \"${CHECK_CPU_TEST_PROGRAM}\" ..."
+      ${CHECK_CPU_TEST_PROGRAM}
+      if [ $? -ne 0 ] ; then
+        echo "ERROR: Looks like the current CPU can NOT execute binaries for arm64 CPUs"
+        echo "       Note: To disable this test either use the parameter \"nocpucheck\" or delete or rename the file \"${CHECK_CPU_TEST_PROGRAM}\" "
+        CONTINUE=${__FALSE}
+      fi
+    else
+      echo "The CPU check program  \"${CHECK_CPU_TEST_PROGRAM}\" does not exist or is not executable - no CPU check done"
+    fi
+  fi
+fi
+
+# ---------------------------------------------------------------------
 
 if [ ${CONTINUE} = ${__TRUE} ] ; then
 
   echo "Running as user \"${CUR_USER}\" "
-  
+
   if [[ $0 == *init_clang*_env* ]] ; then
     echo
     echo "*******************************************************************************************"
     echo " WARNING: The script $0 must be sourced in "
     echo "*******************************************************************************************"
     echo
-    STANDALONE_SCRIPT=${__TRUE}                 
+    STANDALONE_SCRIPT=${__TRUE} 
   fi
 
 # ---------------------------------------------------------------------
@@ -259,7 +315,7 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
   LIB_DIRS="${CLANG_SYSROOT}/usr/lib"
 
   OBJ_DIRS=""
-  
+
   INCLUDE_DIRS="${CLANG_SYSROOT}/usr/include ${CLANG_DIR}/include"
 
   BIN_DIRS="${CLANG_DIR}/bin"
@@ -283,13 +339,13 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
       OBJ_DIRS="${OBJ_DIRS} ${SYSROOT_LIB_DIR}/${API}"
 
       LIB_DIRS="${LIB_DIRS} ${SYSROOT_LIB_DIR}"
-            
+
       ${TEST} -d ${SYSROOT}/usr/bin && BIN_DIRS="${BIN_DIRS} ${SYSROOT}/usr/bin"
 
       SYSROOT_CONFIGURE_OPTION="--sysroot ${SYSROOT}"
 
     else
-      echo "WARNING: The sysroot directory ${SYSROOT} does not exist"	  
+      echo "WARNING: The sysroot directory ${SYSROOT} does not exist"	
     fi
   fi
 
@@ -308,9 +364,13 @@ fi
 # ---------------------------------------------------------------------
 
 if [ ${CONTINUE} = ${__TRUE} ] ; then
-  
+
   echo
   echo "Preparing the clang environment for creating binaries for the CPU type ${CPU_TYPE}"
+
+  if [ "${CUR_CPU_TYPE}"x != "${CPU_TYPE}"x ] ; then
+    echo "The current CPU type is \"${CUR_CPU_TYPE}\" "
+  fi
 
   if [ "${TARGET_ROOT}"x != ""x ] ; then
     if ${TEST} -d  "${TARGET_ROOT}"  ; then
@@ -318,12 +378,12 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
       BIN_DIRS="${BIN_DIRS} ${TARGET_ROOT}/usr/bin"
       LIB_DIRS="${LIB_DIRS} ${TARGET_ROOT}/usr/lib"
     else
-     echo "INFO: The target root directory ${TARGET_ROOT} does not exist"  
+     echo "INFO: The target root directory ${TARGET_ROOT} does not exist"
     fi
   fi
-  
+
   echo ""
-  
+
   printf "%-90s %s\n" "Using clang ${CLANG_VERSION}" 
   printf "\n"
 
@@ -340,9 +400,9 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
   fi
 
   printf "\n"
-  
+
   echo ""
-  
+
   for CUR_DIR in ${BIN_DIRS} ; do
     echo ":${PATH}:" | grep ":${CUR_DIR}:" >/dev/null
     if [ $? -ne 0 ] ; then
@@ -358,23 +418,23 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
     if ! ${TEST} -d "${CUR_DIR}" ; then
       echo "WARNING: The directory with include files \"${CUR_DIR}\" does not exist"
     fi
-  
+
     echo "${CFLAGS} " | grep -- "-I${CUR_DIR} " >/dev/null
     if [ $? -ne 0 ] ; then
     echo "${CFLAGS} " | grep -- "-I${CUR_DIR} " >/dev/null
       CFLAGS="${CFLAGS} -I${CUR_DIR}"
     fi
-  
+
     echo "${CPPFLAGS} " | grep -- "-I${CUR_DIR} " >/dev/null
     if [ $? -ne 0 ] ; then
       CPPFLAGS="${CPPFLAGS} -I${CUR_DIR}"
     fi
-  
+
     echo "${CXXFLAGS} " | grep -- "-I${CUR_DIR} " >/dev/null
     if [ $? -ne 0 ] ; then
       CXXFLAGS="${CXXFLAGS} -I${CUR_DIR}"
     fi
-  
+
   done
 
  
@@ -382,7 +442,7 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
     if ! ${TEST} -d "${CUR_DIR}" ; then
       echo "WARNING: The directory with libraries \"${CUR_DIR}\" does not exist"
     fi
-  
+
     echo "${LDFLAGS} " | grep -- "-L${CUR_DIR} " >/dev/null
     if [ $? -ne 0 ] ; then
       LDFLAGS="${LDFLAGS} -L${CUR_DIR}"
@@ -394,28 +454,28 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
     if ! ${TEST} -d "${CUR_DIR}" ; then
       echo "WARNING: The directory with object files \"${CUR_DIR}\" does not exist"
     fi
-  
+
     echo "${LDFLAGS} " | grep -- "-B${CUR_DIR}/ " >/dev/null
     if [ $? -ne 0 ] ; then
       LDFLAGS="${LDFLAGS} -B${CUR_DIR}/"
     fi
   done
-  
+
 
   if [ "${SYSROOT_CONFIGURE_OPTION}"x != ""x ] ; then 
     echo "$CFLAGS" | grep -- " --sysroot" >/dev/null ||
       CFLAGS="$CFLAGS --sysroot=${SYSROOT}"
-  
+
     echo "$CPPFLAGS" | grep -- " --sysroot" >/dev/null ||
       CPPFLAGS="$CPPFLAGS --sysroot=${SYSROOT}"
-  
+
     echo "$CXXLAGS" | grep -- " --sysroot " >/dev/null ||
       CXXFLAGS="$CXXFLAGS --sysroot=${SYSROOT}"
-  
-  
+
+
     echo "$LDFLAGS" | grep -- " --sysroot " >/dev/null ||
       LDFLAGS="$LDFLAGS --sysroot=${SYSROOT}"
-    
+
   fi
 
   echo " $LDFLAGS " | grep -- " -lc " >/dev/null ||
@@ -429,8 +489,8 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
       export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:${CUR_PKG_CONFIG_PATH}"
     fi 
   done
-  
-  
+
+
   export CFLAGS CXXFLAGS CPPFLAGS LDFLAGS SYSROOT TARGET_ROOT API NDK SYSROOT PKG_CONFIG_PATH
 
   export CC="${CLANG_DIR}/bin/clang"
@@ -448,13 +508,13 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
   fi
 
   echo "Environment variables used:"
-  
+
   CUR_VAR_NAME_FIELD_LENGTH=25
-  
+
   printf "\n"
   printf "%-${CUR_VAR_NAME_FIELD_LENGTH}s %s\n" "PATH is now:"             "${PATH}"
   printf "\n"
-  
+
   printf "%-${CUR_VAR_NAME_FIELD_LENGTH}s %s\n" "LD_LIBRARY_PATH:"         "${LD_LIBRARY_PATH}"
   printf "\n"
   printf "%-${CUR_VAR_NAME_FIELD_LENGTH}s %s\n" "API is now:"              "${API}"
@@ -471,7 +531,7 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
   printf "\n"
   printf "%-${CUR_VAR_NAME_FIELD_LENGTH}s %s\n" "LDFLAGS are now:"         "${LDFLAGS}"
   printf "\n"
-  
+
   for CUR_VAR in CC CXX CPP CXXCPP AR AS LD RANLIB STRIP PKG_CONFIG PKG_CONFIG_PATH ; do
     eval CUR_VALUE="\$$CUR_VAR"
     printf "%-${CUR_VAR_NAME_FIELD_LENGTH}s %s\n" "${CUR_VAR} is now:" "${CUR_VALUE}"
@@ -507,22 +567,21 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
 
   export CC=${CLANG}
   export LD=${LLD}
-  
-  
+
   # define aliase
   #
   echo "Define some aliase ..."
-  
+
   NEW_ALIAS=""
 
   alias sysroot="cd ${CLANG_SYSROOT}; pwd"
-  
+
   alias setlibpath="export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
  
   alias addlib='LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/data/local/tmp/develop/sysroot/usr/lib '
 
   alias cp_crt_libs='cp ${NDK_DIR}/sysroot/usr/lib/${CPU_TYPE}-linux-android/${API}/crt*.o .'
-  
+
   NEW_ALIAS="sysroot setlibpath addlib"
 
   for i in vi find tar bash sed awk dd nano curl ; do
@@ -537,23 +596,22 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
     alias $i
   done
 
-  
+
   echo ""
-  
-  
+
   if [ ${ROOT_ACCESS_AVAILABLE} = ${__TRUE} ] ; then
-    
+
     if [ "${ROOT_PREFIX}"x = ""x ] ; then
       echo "The user running this script is the user \"root\" "
     else
       echo "Root access is enabled on this machine"
       echo ""
-    
+
       if [ "${MAGISKPOLICY}"x != ""x ] ; then
-    
+
         if which tmux 2>/dev/null 1>dev/null ; then
           echo "Enabling socket access for the user \"shell\"  (this is necessary to use tmux)..."
-    
+
           ${ROOT_PREFIX} ${MAGISKPOLICY} '--live "allow shell shell_data_file sock_file { create getattr setattr write unlink }"  '
           ${ROOT_PREFIX} ${MAGISKPOLICY} '--live "allow shell devpts chr_file { read write open }"'
         fi
@@ -562,13 +620,13 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
         ${ROOT_PREFIX} ${MAGISKPOLICY} '--live "allow shell shell_data_file file link" '
 
         echo "Enabling creating and using fifos for the user \"shell\" ..."
-        ${ROOT_PREFIX} 'magiskpolicy --live "allow shell shell_data_file fifo_file { create read open write }" '      
+        ${ROOT_PREFIX} 'magiskpolicy --live "allow shell shell_data_file fifo_file { create read open write }" '
 
       else
         LogDebugMsg "Magisk is not installed on this machine - can not enable tmux for non-root user"
       fi
     fi
-    
+
     echo ""
   else
     LogDebugMsg  "root access is NOT enabled on this machine"
@@ -583,7 +641,7 @@ if [ ${CONTINUE} = ${__TRUE} ] ; then
 
   echo "$PS1" | grep "\[clang19" 2>/dev/null >/dev/null || export PS1="[clang19 toolchain] $PS1" 
 
-  CLANG_ENV_INIT_DONE=${__TRUE}  
+  CLANG_ENV_INIT_DONE=${__TRUE}
 
   echo ""
 
