updated gzip to version 1.15

diff --git a/sysroot/usr/bin/gzexe b/sysroot/usr/bin/gzexe
--- a/sysroot/usr/bin/gzexe
+++ b/sysroot/usr/bin/gzexe
@@ -1,4 +1,4 @@
-#!/system/bin/sh
+#!/bin/sh
 # gzexe: compressor for Unix executables.
 # Use this only for binaries that you do not use frequently.
 #
@@ -8,12 +8,12 @@
 # We also try to retain the original file permissions on the compressed file.
 # For safety reasons, gzexe will not create setuid or setgid shell scripts.
 
-# WARNING: the first line of this file must be either : or #!/system/bin/sh
+# WARNING: the first line of this file must be either : or #!/bin/sh
 # The : is required for some old versions of csh.
-# On Ultrix, /system/bin/sh is too buggy, change the first line to: #!/system/bin/sh5
+# On Ultrix, /bin/sh is too buggy, change the first line to: #!/bin/sh5
 
 
-# Copyright (C) 1998, 2002, 2004, 2006-2007, 2010-2023 Free Software
+# Copyright (C) 1998, 2002, 2004, 2006-2007, 2010-2026 Free Software
 # Foundation, Inc.
 # Copyright (C) 1993 Jean-loup Gailly
 
@@ -27,17 +27,16 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 
-# You should have received a copy of the GNU General Public License along
-# with this program; if not, write to the Free Software Foundation, Inc.,
-# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
 tab='	'
 nl='
 '
 IFS=" $tab$nl"
 
-version='gzexe (gzip) 1.13
-Copyright (C) 2023 Free Software Foundation, Inc.
+version='gzexe (gzip) 1.15
+Copyright (C) 2026 Free Software Foundation, Inc.
 This is free software.  You may redistribute copies of it under the terms of
 the GNU General Public License <https://www.gnu.org/licenses/gpl.html>.
 There is NO WARRANTY, to the extent permitted by law.
@@ -87,22 +86,22 @@ for i do
   esac
   if test ! -f "$file" || test ! -r "$file"; then
     res=$?
-    printf >&2 '%s\n' "$0: $i is not a readable regular file"
+    printf >&2 '%s\n' "$0: operand is not a readable regular file"
     continue
   fi
   if test $decomp -eq 0; then
     case `LC_ALL=C sed -n -e 1d -e '/^skip=[0-9][0-9]*$/p' -e 2q "$file"` in
     skip=[0-9] | skip=[0-9][0-9] | skip=[0-9][0-9][0-9])
-      printf >&2 '%s\n' "$0: $i is already gzexe'd"
+      printf >&2 '%s\n' "$0: file is already gzexe'd"
       continue;;
     esac
   fi
   if test -u "$file"; then
-    printf >&2 '%s\n' "$0: $i has setuid permission, unchanged"
+    printf >&2 '%s\n' "$0: file has setuid permission, unchanged"
     continue
   fi
   if test -g "$file"; then
-    printf >&2 '%s\n' "$0: $i has setgid permission, unchanged"
+    printf >&2 '%s\n' "$0: file has setgid permission, unchanged"
     continue
   fi
   case /$file in
@@ -110,14 +109,14 @@ for i do
   */dirname | */expr | */gzip | \
   */ln | */mkdir | */mktemp | */mv | */printf | */rm | \
   */sed | */sh | */sleep | */test | */tail)
-    printf >&2 '%s\n' "$0: $i might depend on itself"; continue;;
+    printf >&2 '%s\n' "$0: file might depend on itself"; continue;;
   esac
 
   dir=`dirname "$file"` || dir=$TMPDIR
-  test -d "$dir" && test -w "$dir" && test -x "$dir" || dir=/tmp
+  test -d "$dir" && test -w "$dir" && test -x "$dir" || dir=/data/local/tmp/sysroot/tmp
   test -n "$tmp" && rm -f "$tmp"
   if test -z "$mktemp_status"; then
-    type mktemp >/dev/null 2>&1
+    command -v mktemp >/dev/null 2>&1
     mktemp_status=$?
   fi
   case $dir in
@@ -128,9 +127,10 @@ for i do
     tmp=`mktemp "${dir}gzexeXXXXXXXXX"`
   else
     tmp=${dir}gzexe$$
+    (umask 77; set -C; > "$tmp")
   fi && { cp -p "$file" "$tmp" 2>/dev/null || cp "$file" "$tmp"; } || {
     res=$?
-    printf >&2 '%s\n' "$0: cannot copy $file"
+    printf >&2 '%s\n' "$0: cannot copy file"
     continue
   }
   if test -w "$tmp"; then
@@ -139,14 +139,15 @@ for i do
     writable=0
     chmod u+w "$tmp" || {
       res=$?
-      printf >&2 '%s\n' "$0: cannot chmod $tmp"
+      printf >&2 '%s\n' "$0: cannot chmod tmp directory"
       continue
     }
   fi
   if test $decomp -eq 0; then
     (cat <<'EOF' &&
-#!/system/bin/sh
-skip=49
+#!/bin/sh
+skip=50
+set -e
 
 tab='	'
 nl='
@@ -165,9 +166,9 @@ trap 'res=$?
 case $TMPDIR in
   / | /*/) ;;
   /*) TMPDIR=$TMPDIR/;;
-  *) TMPDIR=/tmp/;;
+  *) TMPDIR=/data/local/tmp/sysroot/tmp/;;
 esac
-if type mktemp >/dev/null 2>&1; then
+if command -v mktemp >/dev/null 2>&1; then
   gztmpdir=`mktemp -d "${TMPDIR}gztmpXXXXXXXXX"`
 else
   gztmpdir=${TMPDIR}gztmp$$; mkdir $gztmpdir
@@ -196,13 +197,13 @@ fi; exit $res
 EOF
     gzip -cv9 "$file") > "$tmp" || {
       res=$?
-      printf >&2 '%s\n' "$0: compression not possible for $i, file unchanged."
+      printf >&2 '%s\n' "$0: compression not possible, file unchanged."
       continue
     }
 
   else
     # decompression
-    skip=44
+    skip=50
     skip_line=`LC_ALL=C sed -e 1d -e 2q "$file"`
     case $skip_line in
     skip=[0-9] | skip=[0-9][0-9] | skip=[0-9][0-9][0-9])
@@ -214,13 +215,13 @@ EOF
     esac
     tail $tail_n +$skip "$file" | gzip -cd > "$tmp" || {
       res=$?
-      printf >&2 '%s\n' "$0: $i probably not in gzexe format, file unchanged."
+      printf >&2 '%s\n' "$0: file probably not in gzexe format, file unchanged."
       continue
     }
   fi
   test $writable -eq 1 || chmod u-w "$tmp" || {
     res=$?
-    printf >&2 '%s\n' "$0: $tmp: cannot chmod"
+    printf >&2 '%s\n' "$0: cannot chmod tmp file"
     continue
   }
   ln -f "$file" "$file~" 2>/dev/null || {
@@ -228,12 +229,12 @@ EOF
     rm -f "$file~" && cp -p "$file" "$file~"
   } || {
     res=$?
-    printf >&2 '%s\n' "$0: cannot backup $i as $i~"
+    printf >&2 '%s\n' "$0: cannot backup file as file~"
     continue
   }
   mv -f "$tmp" "$file" || {
     res=$?
-    printf >&2 '%s\n' "$0: cannot rename $tmp to $i"
+    printf >&2 '%s\n' "$0: cannot rename tmp file to destination"
     continue
   }
   tmp=
